### ISSUE TITLE
Client crashed (x'd out on me twice within 20 minutes) [1 of 3 clients running] 

### ISSUE THREAD

**Issue by w355osrs** [open-osrs/runelite#1123]
Got crashed twice. 3 clients up. One at Rune drags, rc'ing bloods, and COX. First COX client crashed. Then started new client up again and the one rc'ing bloods crashed. CPU was @ around 30% at the time of the crash. 

About a week or so ago when I was in chambers I crashed as well. Couldn't find any evidence of a "crash" in the logs (i.e. ctrl f "crash" resulted in nothing). What I copied and pasted was the client folder under logs of the most recent date modified. Thanks. Please help me in how I can address this issue so there can be a solution. 

Log linked here because too many characters: https://pastebin.com/tPhtERU8

**Comment by Kyleeld** [comment]
can you confirm if this is still an issue?

**Comment by w355osrs** [comment]
Yes

**Comment by w355osrs** [comment]
Just happened after opening up a second client and logging in.

2019-08-04 00:31:23 [pool-5-thread-11] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2019-08-04 00:31:23 [RuneLite] INFO  n.r.client.plugins.PluginManager - Plugin instantiation took 815ms
2019-08-04 00:31:23 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,552,249,817x542,layout=java.awt.BorderLayout,title=RuneLite,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,8,31,801x503,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2019-08-04 00:31:25 [Client] WARN  net.runelite.client.callback.Hooks - error during main loop tasks
java.lang.NullPointerException: Both parameters are null
	at com.google.common.base.MoreObjects.firstNonNull(MoreObjects.java:61)
	at net.runelite.client.chat.ChatMessageManager.add(ChatMessageManager.java:577)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at net.runelite.client.chat.ChatMessageManager.process(ChatMessageManager.java:555)
	at net.runelite.client.callback.Hooks.clientMainLoop(Hooks.java:179)
	at client.draw(client.java:1426)
	at client.ag(client.java)
	at bz.s(bz.java:390)
	at bz.run(bz.java:344)
	at java.lang.Thread.run(Thread.java:748)
2019-08-04 00:31:27 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2019-08-04 00:31:27 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 6668ms. Uptime: 12774ms
2019-08-04 00:31:28 [pool-3-thread-1] INFO  n.r.c.p.l.LootTrackerPlugin - Loaded 634 locally stored loot records
2019-08-04 00:31:29 [pool-3-thread-1] INFO  n.r.client.discord.DiscordService - Discord RPC service is ready with user W355.
2019-08-04 00:31:45 [Client] WARN  net.runelite.client.callback.Hooks - error during main loop tasks
java.lang.NullPointerException: Both parameters are null
	at com.google.common.base.MoreObjects.firstNonNull(MoreObjects.java:61)
	at net.runelite.client.chat.ChatMessageManager.add(ChatMessageManager.java:577)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at net.runelite.client.chat.ChatMessageManager.process(ChatMessageManager.java:555)
	at net.runelite.client.callback.Hooks.clientMainLoop(Hooks.java:179)
	at client.draw(client.java:1426)
	at client.ag(client.java)
	at bz.s(bz.java:390)
	at bz.run(bz.java:344)
	at java.lang.Thread.run(Thread.java:748)
2019-08-04 00:32:02 [Client] WARN  net.runelite.client.callback.Hooks - error during main loop tasks
java.lang.NullPointerException: Both parameters are null
	at com.google.common.base.MoreObjects.firstNonNull(MoreObjects.java:61)
	at net.runelite.client.chat.ChatMessageManager.add(ChatMessageManager.java:577)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at net.runelite.client.chat.ChatMessageManager.process(ChatMessageManager.java:555)
	at net.runelite.client.callback.Hooks.clientMainLoop(Hooks.java:179)
	at client.draw(client.java:1426)
	at client.ag(client.java)
	at bz.s(bz.java:390)
	at bz.run(bz.java:344)
	at java.lang.Thread.run(Thread.java:748)

**Comment by w355osrs** [comment]
[client.log](https://github.com/runelite-extended/runelite/files/3479394/client.log)

**Comment by xKylee** [comment]
a fix for your error is about to be implemented. will need to revisit once next update goes live.

**Comment by xKylee** [comment]
can you confirm if this is still an issue in 2.1.4.0?
