### ISSUE TITLE
banlist: Index Out Of Bounds Exception

### ISSUE THREAD

**Issue by Ganom** [open-osrs/runelite#1370]
```java
2019-08-16 22:06:17 [OkHttp Dispatcher] ERROR net.runelite.client.RuneLite - Uncaught exception:
java.lang.StringIndexOutOfBoundsException: String index out of range: 10
	at java.lang.String.charAt(String.java:658)
	at java.util.regex.Pattern$BmpCharProperty.match(Pattern.java:3799)
	at java.util.regex.Pattern$Start.match(Pattern.java:3463)
	at java.util.regex.Matcher.search(Matcher.java:1248)
	at java.util.regex.Matcher.find(Matcher.java:637)
	at java.util.regex.Matcher.replaceAll(Matcher.java:951)
	at net.runelite.client.util.Text.removeTags(Text.java:82)
	at net.runelite.client.util.Text.standardize(Text.java:93)
	at net.runelite.client.plugins.banlist.BanListPlugin$3.lambda$onResponse$0(BanListPlugin.java:471)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at net.runelite.client.plugins.banlist.BanListPlugin$3.onResponse(BanListPlugin.java:471)
	at okhttp3.RealCall$AsyncCall.run(RealCall.kt:138)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by se7enAte9** [comment]
I'm not entirely sure how java interprets the nbsp, but if it sees the backslash character in `\u00A0`, the [API](https://docs.oracle.com/javase/8/docs/api/java/util/regex/Matcher.html#replaceAll-java.lang.String-) says `replaceAll` can run into issues.

If that is the issue, replacing nbsp with space before removing tags in `Text.standardize(String str)` at [#L93](https://github.com/runelite-extended/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/util/Text.java#L93) like so: `return removeTags(str.replace('\u00A0', ' ')).trim().toLowerCase();` may fix this issue.
