### ISSUE TITLE
Player indicator spam

### ISSUE THREAD

**Issue by Crystalknoct** [open-osrs/runelite#1608]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
sitting at ge
**To Reproduce**
1. Go to 'Ge id assume'
2. Click on 'not sure what caused tbf'
3. Scroll down to 'the list'
2019-09-15 03:15:51 [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - Error during overlay rendering
java.lang.NullPointerException: null
	at java.base/java.util.Objects.requireNonNull(Objects.java:221)
	at net.runelite.client.plugins.playerindicators.PlayerIndicatorsOverlay.drawSceneOverlays(PlayerIndicatorsOverlay.java:128)
	at net.runelite.client.plugins.playerindicators.PlayerIndicatorsOverlay.lambda$render$0(PlayerIndicatorsOverlay.java:84)
	at net.runelite.client.plugins.playerindicators.PlayerIndicatorsService.forEachPlayer(PlayerIndicatorsService.java:110)
	at net.runelite.client.plugins.playerindicators.PlayerIndicatorsOverlay.render(PlayerIndicatorsOverlay.java:84)
	at net.runelite.client.ui.overlay.OverlayRenderer.safeRender(OverlayRenderer.java:534)
	at net.runelite.client.ui.overlay.OverlayRenderer.render(OverlayRenderer.java:278)
	at net.runelite.client.callback.Hooks.drawAboveOverheads(Hooks.java:434)
	at dt.checkTextures(dt.java:56)
	at dt.v(dt.java:116)
	at bs.fn(bs.java:4256)
	at gd.ik(gd.java:9047)
	at ap.ii(ap.java:8936)
	at client.fx(client.java:4048)
	at client.av(client.java:1323)
	at bn.m(bn.java:371)
	at bn.run(bn.java:325)
	at java.base/java.lang.Thread.run(Thread.java:834)
**Expected behavior**
Nothing really happened to the plugin just error puke
**Screenshots**

**Environment (please complete the following information):**
 - OS: [windows]
 - RuneLite version: [1.5.34]
 - Launcher version: [2.1.5.1]

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by stone-wall** [comment]
was fixed at some point
