### ISSUE TITLE
Wild location stop updating after entering Fire Giants

### ISSUE THREAD

**Issue by whs** [open-osrs/runelite#1720]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
After entering the fire giants area, wilderness location overlay stop updating. This include out of wilderness where the text is still appearing

The text even appear after a relog

**To Reproduce**
1. Enable wild location. The options I enable are "Draw Overlay" "PvP World" "Show Loc Names World Map"
2. Enter fire giants area

I'm not sure when this start occuring, the text says "SE of Wildy Agility Course". But a few things I did that could help

- Use the diary shortcut from entrance to fire giants
- Enter the mage bank and teleport out

**Expected behavior**
The location name should disappear when out of wilderness

**Screenshots**

![image](https://user-images.githubusercontent.com/345483/66254648-44b66380-e7a3-11e9-88f7-b0ca2647fbb0.png)

**Environment (please complete the following information):**
 - OS: Arch Linux
 - RuneLite version: 42b9a9b244e1f1d71819d348a46e05de40d0a0ee
 - Launcher version: N/A (build from source)

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

```
2019-10-05 14:06:36 [Client] ERROR n.runelite.client.eventbus.EventBus - java.lang.NullPointerException
        at java.base/java.util.Objects.requireNonNull(Objects.java:221)
        at net.runelite.client.game.WorldLocation.location(WorldLocation.java:266)
        at net.runelite.client.plugins.wildernesslocations.WildernessLocationsPlugin.onGameTick(WildernessLocationsPlugin.java:182)
        at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
        at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:62)
        at io.reactivex.internal.operators.observable.ObservableFilter$FilterObserver.onNext(ObservableFilter.java:52)
        at com.jakewharton.rxrelay2.PublishRelay$PublishDisposable.onNext(PublishRelay.java:180)
        at com.jakewharton.rxrelay2.PublishRelay.accept(PublishRelay.java:145)
        at com.jakewharton.rxrelay2.SerializedRelay.accept(SerializedRelay.java:57)
        at net.runelite.client.eventbus.EventBus.post(EventBus.java:81)
        at net.runelite.client.callback.Hooks.clientMainLoop(Hooks.java:179)
        at client.draw(client.java:1463)
        at client.ax(client.java)
        at bh.f(bh.java:380)
        at bh.run(bh.java:334)
        at java.base/java.lang.Thread.run(Thread.java:844)
```
```

**Comment by xKylee** [comment]
this isnt just fire giants, it happens anytime you go underground in the wilderness.
