### ISSUE TITLE
Master build failing

### ISSUE THREAD

**Issue by chrisjohnson** [open-osrs/runelite#1875]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
```

cjohnson at CMMC02TN0LRG8WL in ~/runelite (remotes/upstream/master)
$ ./gradlew build -x test -x:runelite-client:checkstyleMain --rerun-tasks --no-build-cache --stacktrace -x checkstyleMain -x checkstyleTest
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

> Task :buildSrc:jar
:jar: No valid plugin descriptors were found in META-INF/gradle-plugins

> Task :buildSrc:validateTaskProperties
Task property validation finished with warnings:
  - Warning: Type 'FernflowerTask': property 'getOutputDir' is annotated with @PathSensitive that is not allowed for @OutputDirectory properties.
Configuration on demand is an incubating feature.

> Task :runelite-api:compileJava
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :runescape-api:compileJava
Note: /Users/cjohnson/runelite/runescape-api/src/main/java/net/runelite/rs/api/RSWidget.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/cjohnson/runelite/runescape-api/src/main/java/net/runelite/rs/api/RSClient.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :runelite-mixins:compileJava
Note: /Users/cjohnson/runelite/runelite-mixins/src/main/java/net/runelite/mixins/RSModelMixin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :http-api:compileJava
Note: /Users/cjohnson/runelite/http-api/src/main/java/net/runelite/http/api/config/ConfigClient.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :runescape-client:compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :cache:compileJava
Note: /Users/cjohnson/runelite/cache/src/main/java/net/runelite/cache/definitions/loaders/InterfaceLoader.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :runelite-script-assembler-plugin:assembleMojo
[debug] Assembling /Users/cjohnson/runelite/runelite-client/src/main/scripts/SendPrivateMessage.rs2asm
ANTLR Tool version 4.6 used for code generation does not match the current runtime version 4.7.2ANTLR Tool version 4.6 used for code generation does not match the current runtime version 4.7.2[debug] Assembling /Users/cjohnson/runelite/runelite-client/src/main/scripts/UpdateBankPin.rs2asm
[debug] Assembling /Users/cjohnson/runelite/runelite-client/src/main/scripts/XpDropChanged.rs2asm
[debug] Assembling /Users/cjohnson/runelite/runelite-client/src/main/scripts/DestroyOnOpKey.rs2asm
[debug] Assembling /Users/cjohnson/runelite/runelite-client/src/main/scripts/TriggerBankLayout.rs2asm
[debug] Assembling /Users/cjohnson/runelite/runelite-client/src/main/scripts/FakeXPDrops.rs2asm
[debug] Assembling /Users/cjohnson/runelite/runelite-client/src/main/scripts/MagicSpellBookRedraw.rs2asm
[debug] Assembling /Users/cjohnson/runelite/runelite-client/src/main/scripts/ToplevelChatboxBackground.rs2asm
[debug] Assembling /Users/cjohnson/runelite/runelite-client/src/main/scripts/GELayout.rs2asm
[debug] Assembling /Users/cjohnson/runelite/runelite-client/src/main/scripts/ChatBuilder.rs2asm
[debug] Assembling /Users/cjohnson/runelite/runelite-client/src/main/scripts/ChatSplitBuilder.rs2asm
[debug] Assembling /Users/cjohnson/runelite/runelite-client/src/main/scripts/SendPublicMessage.rs2asm
[debug] Assembling /Users/cjohnson/runelite/runelite-client/src/main/scripts/BankLayoutTabSeparator.rs2asm
[debug] Assembling /Users/cjohnson/runelite/runelite-client/src/main/scripts/ChatboxInputWidgetBuilder.rs2asm
[debug] Assembling /Users/cjohnson/runelite/runelite-client/src/main/scripts/SkillTabBuilder.rs2asm
[debug] Assembling /Users/cjohnson/runelite/runelite-client/src/main/scripts/CustomJoinClan.rs2asm
[debug] Assembling /Users/cjohnson/runelite/runelite-client/src/main/scripts/OptionsPanelZoomMouseListener.rs2asm
[debug] Assembling /Users/cjohnson/runelite/runelite-client/src/main/scripts/BankBuildTab.rs2asm
[debug] Assembling /Users/cjohnson/runelite/runelite-client/src/main/scripts/BankSearchLayout.rs2asm
[debug] Assembling /Users/cjohnson/runelite/runelite-client/src/main/scripts/BankSearchFilter.rs2asm
[debug] Assembling /Users/cjohnson/runelite/runelite-client/src/main/scripts/SkillTabTotalLevel.rs2asm
[debug] Assembling /Users/cjohnson/runelite/runelite-client/src/main/scripts/JewelleryBoxInit.rs2asm
[debug] Assembling /Users/cjohnson/runelite/runelite-client/src/main/scripts/CombatInterfaceSP.rs2asm
[debug] Assembling /Users/cjohnson/runelite/runelite-client/src/main/scripts/SpecbarRedraw.rs2asm
[debug] Assembling /Users/cjohnson/runelite/runelite-client/src/main/scripts/ResetChatboxInput.rs2asm
[debug] Assembling /Users/cjohnson/runelite/runelite-client/src/main/scripts/null.rs2asm
[debug] Assembling /Users/cjohnson/runelite/runelite-client/src/main/scripts/DeathkeepBuild.rs2asm
[debug] Assembling /Users/cjohnson/runelite/runelite-client/src/main/scripts/OptionsPanelZoomUpdater.rs2asm
[debug] Assembling /Users/cjohnson/runelite/runelite-client/src/main/scripts/ZoomHandler.rs2asm
[debug] Assembling /Users/cjohnson/runelite/runelite-client/src/main/scripts/PrivateMessage.rs2asm
[debug] Assembling /Users/cjohnson/runelite/runelite-client/src/main/scripts/options_allsounds.rs2asm
[debug] Assembling /Users/cjohnson/runelite/runelite-client/src/main/scripts/ChatboxInput.rs2asm
[debug] Assembling /Users/cjohnson/runelite/runelite-client/src/main/scripts/OptionsPanelRebuilder.rs2asm
[debug] Assembling /Users/cjohnson/runelite/runelite-client/src/main/scripts/OpenBankSearchInput.rs2asm
[debug] Assembling /Users/cjohnson/runelite/runelite-client/src/main/scripts/CommandScript.rs2asm
[debug] Assembling /Users/cjohnson/runelite/runelite-client/src/main/scripts/PvpWidgetBuilder.rs2asm
[debug] Assembling /Users/cjohnson/runelite/runelite-client/src/main/scripts/QuestListShowProgress.rs2asm
[debug] Assembling /Users/cjohnson/runelite/runelite-client/src/main/scripts/GEOffersSetupInit.rs2asm
[debug] Assembling /Users/cjohnson/runelite/runelite-client/src/main/scripts/ScrollWheelZoomHandler.rs2asm
[info] Assembled 39 scripts

> Task :wiki-scraper:compileJava
Note: /Users/cjohnson/runelite/wiki-scraper/src/main/java/net/runelite/data/dump/MediaWikiTemplate.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :cache-updater:compileJava
Note: /Users/cjohnson/runelite/cache-updater/src/main/java/net/runelite/cache/updater/CacheUploader.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :injector-plugin:inject
[main] INFO net.runelite.injector.raw.RasterizerAlpha - Added 1 OR's into static lv.dn(IIIII)V
[main] INFO net.runelite.injector.raw.RasterizerAlpha - Injected 1 DrawAlpha invokes into static lv.di(IIIIII)V
[main] INFO net.runelite.injector.raw.RasterizerAlpha - Added 5 OR's into static lx.m([I[IIIIIII)V
[main] INFO net.runelite.injector.raw.RasterizerAlpha - Added 5 OR's into static lw.q([I[B[IIIIIII)V
[main] INFO net.runelite.injector.raw.RasterizerAlpha - Added 1 OR's into static lv.df(IIII)V
[main] INFO net.runelite.injector.raw.RasterizerAlpha - Added 1 OR's into static lv.dg(IIII)V
[main] INFO net.runelite.injector.raw.RasterizerAlpha - Added 5 OR's into static lx.h([I[IIIIIIII)V
[main] INFO net.runelite.injector.raw.RasterizerAlpha - Injected 1 DrawAlpha invokes into static lx.r([I[IIIIIIIIII)V
[main] INFO net.runelite.injector.raw.RasterizerAlpha - Added 2 OR's into static lv.dy(IIIII)V
[main] INFO net.runelite.injector.raw.RasterizerAlpha - Added 5 OR's into static kx.ap([I[BIIIIIII)V
[main] INFO net.runelite.injector.raw.RasterizerAlpha - Injected 1 DrawAlpha invokes into static kx.ae([I[BIIIIIIII)V
[main] INFO net.runelite.injector.raw.RasterizerAlpha - Added 1 OR's into static lv.dk(III[I[I)V
[main] INFO net.runelite.injector.raw.RasterizerAlpha - Added 1 OR's into lx.ax(IIIIIIII[I[I)V
[main] INFO net.runelite.injector.raw.RasterizerAlpha - Injected 1 DrawAlpha invokes into static lv.da(IIIII)V
[main] INFO net.runelite.injector.raw.RasterizerAlpha - Injected 1 DrawAlpha invokes into static lv.dp(IIIII)V
[main] INFO net.runelite.injector.raw.RasterizerAlpha - Injected 1 DrawAlpha invokes into static lx.w([I[IIIIIIIIIIII)V
[main] INFO net.runelite.injector.raw.RasterizerAlpha - Added 9 OR's into lx.aj(IIIIII)V
[main] INFO net.runelite.injector.raw.RasterizerAlpha - Injected 1 DrawAlpha invokes into static lx.s([I[IIIIIIIII)V
[main] INFO net.runelite.injector.raw.RasterizerAlpha - Added 1 OR's into static lx.x([I[IIIIIIIIIII)V
[main] INFO net.runelite.injector.raw.RasterizerAlpha - Added 1 OR's into lx.ab(IIIIII[I[I)V
[main] INFO net.runelite.injector.raw.RasterizerAlpha - Added 1 OR's into lx.al(IIIIIIDI)V
[main] INFO net.runelite.injector.raw.RasterizerAlpha - Injected 2 DrawAlpha invokes into static lv.dm(IIIII)V
[main] INFO net.runelite.injector.raw.RasterizerAlpha - Added 10 OR's into static eu.h([IIIIII)V
[main] INFO net.runelite.injector.raw.RasterizerAlpha - Injected 5 DrawAlpha invokes into static eu.h([IIIIII)V
[main] INFO net.runelite.injector.raw.RasterizerAlpha - Added 1 OR's into lx.ae(IIII)V
[main] INFO net.runelite.injector.raw.RasterizerAlpha - Added 2 OR's into static lv.dl(IIII)V
[main] INFO net.runelite.injector.raw.RasterizerAlpha - Added 1 OR's into static lv.du(III)V
[main] INFO net.runelite.injector.raw.RasterizerAlpha - Added 6 OR's into static eu.m([IIIIIIII)V
[main] INFO net.runelite.injector.raw.RasterizerAlpha - Injected 6 DrawAlpha invokes into static eu.m([IIIIIIII)V
[main] INFO net.runelite.injector.raw.RasterizerAlpha - Added 2 OR's into static lv.ds(IIIIII[BIZ)V
[main] INFO net.runelite.injector.raw.RasterizerAlpha - Added 1 OR's into static lw.l([I[B[IIIIIIIIII)V
[main] INFO net.runelite.injector.raw.RasterizerAlpha - Injected 20 DrawAlpha invokes and 62 ors
[main] INFO net.runelite.injector.MixinInjector - Added javax inject to client.callbacks
[main] INFO net.runelite.injector.MixinInjector - Added javax inject to client.logger
[main] INFO net.runelite.injector.MixinInjector - Added javax named to client.logger
[main] INFO net.runelite.injector.MixinInjector - Replaced net.runelite.asm.attributes.code.instructions.ANewArray@24b8fc34 in client.getSprites(Lnet/runelite/api/IndexDataBase;II)[Lnet/runelite/rs/api/RSSprite; type Lnet/runelite/rs/api/RSSprite; with type Llx;
[main] INFO net.runelite.injector.MixinInjector - Replaced net.runelite.asm.attributes.code.instructions.ANewArray@30efe833 in static client.rl$$clinit3()V type Lnet/runelite/rs/api/RSPlayer; with type Lbj;
Exception in thread "main" net.runelite.injector.InjectionException: Failed to find the deob method getModel for mixin ClassFile{name=net/runelite/mixins/RSWidgetMixin}
        at net.runelite.injector.MixinInjector.injectMethods(MixinInjector.java:348)
        at net.runelite.injector.MixinInjector.inject(MixinInjector.java:157)
        at net.runelite.injector.MixinInjector.inject(MixinInjector.java:139)
        at net.runelite.injector.Inject.run(Inject.java:211)
        at net.runelite.injector.Injector.inject(Injector.java:70)
        at net.runelite.injector.Injector.main(Injector.java:59)

> Task :injector-plugin:inject FAILED

> Task :http-service:compileJava
Note: /Users/cjohnson/runelite/http-service/src/main/java/net/runelite/http/service/SpringWebMvcConfigurer.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/cjohnson/runelite/http-service/src/main/java/net/runelite/http/service/config/ConfigService.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :runelite-client:compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':injector-plugin:inject'.
> Process 'command '/Library/Java/JavaVirtualMachines/openjdk-11.0.2.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':injector-plugin:inject'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:166)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:163)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:191)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:156)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:108)
        at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionOutputsTaskExecuter.execute(ResolveBeforeExecutionOutputsTaskExecuter.java:67)
        at org.gradle.api.internal.tasks.execution.StartSnapshotTaskInputsBuildOperationTaskExecuter.execute(StartSnapshotTaskInputsBuildOperationTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.ResolveAfterPreviousExecutionStateTaskExecuter.execute(ResolveAfterPreviousExecutionStateTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:94)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:355)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/openjdk-11.0.2.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1
        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:409)
        at org.gradle.process.internal.DefaultJavaExecAction.execute(DefaultJavaExecAction.java:40)
        at org.gradle.api.tasks.JavaExec.exec(JavaExec.java:121)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:103)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:49)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:42)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:717)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:684)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$5.run(ExecuteActionsTaskExecuter.java:476)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:461)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:444)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$200(ExecuteActionsTaskExecuter.java:93)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:237)
        at org.gradle.internal.execution.steps.ExecuteStep.lambda$execute$1(ExecuteStep.java:33)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:33)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:26)
        at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:58)
        at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:35)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:48)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:33)
        at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:39)
        at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:73)
        at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:54)
        at org.gradle.internal.execution.steps.CatchExceptionStep.execute(CatchExceptionStep.java:35)
        at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:51)
        at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:45)
        at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:31)
        at org.gradle.internal.execution.steps.CacheStep.executeWithoutCache(CacheStep.java:208)
        at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:70)
        at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:45)
        at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:49)
        at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:43)
        at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:32)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:38)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:24)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:96)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:89)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:54)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:38)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:76)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:37)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:36)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:26)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:90)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:48)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:69)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:47)
        at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:140)
        ... 35 more


* Get more help at https://help.gradle.org

BUILD FAILED in 1m 28s
45 actionable tasks: 45 executed

cjohnson at CMMC02TN0LRG8WL in ~/runelite (remotes/upstream/master)
$ java -version
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
```

**Environment (please complete the following information):**
 - OS: macOS
 - RuneLite version: master HEAD
 - Launcher version: master HEAD

**Comment by f0rmatme** [comment]
-x test -x:runelite-client:checkstyleMain --rerun-tasks --no-build-cache --stacktrace

try a fresh clone
