### ISSUE TITLE
ToB game crash

### ISSUE THREAD

**Issue by Owain94** [open-osrs/runelite#1917]
```2019-11-07 16:05:05 [Client] ERROR n.runelite.client.eventbus.EventBus - Runtime Exception in eventbus
java.lang.NullPointerException: null
    at net.runelite.client.menus.MenuManager.lambda$removeSwaps$4(MenuManager.java:757)
    at java.base/java.util.Collection.removeIf(Unknown Source)
    at net.runelite.client.menus.MenuManager.removeSwaps(MenuManager.java:757)
    at net.runelite.client.plugins.theatre.rooms.nylocas.NyloHandler.onMenuOptionClicked(NyloHandler.java:408)
    at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
    at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:62)
    at io.reactivex.internal.operators.observable.ObservableFilter$FilterObserver.onNext(ObservableFilter.java:52)
    at com.jakewharton.rxrelay2.PublishRelay$PublishDisposable.onNext(PublishRelay.java:180)
    at com.jakewharton.rxrelay2.PublishRelay.accept(PublishRelay.java:145)
    at com.jakewharton.rxrelay2.SerializedRelay.accept(SerializedRelay.java:57)
    at net.runelite.client.eventbus.EventBus.post(EventBus.java:117)
    at net.runelite.client.callback.Hooks.post(Hooks.java:161)
    at bm.io(bm.java:1388)
    at f.kw(f.java:10970)
    at client.fq(client.java:3722)
    at client.ae(client.java:1614)
    at bg.av(bg.java:355)
    at bg.run(bg.java:334)
    at java.base/java.lang.Thread.run(Unknown Source)

**Comment by Owain94** [comment]
Sure, will do @github-actions[bot]

**Comment by Lucwousin** [comment]
This is cause the `target` field in ComparableEntries can be null
