### ISSUE TITLE
DiscordPlugin: ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Owain94** [open-osrs/runelite#1949]
```java
java.lang.ArrayIndexOutOfBoundsException: Index 4193772 out of bounds for length 13
    at net.runelite.api.coords.WorldPoint.fromLocalInstance(WorldPoint.java:178)
    at net.runelite.client.plugins.discord.DiscordPlugin.checkForAreaUpdate(DiscordPlugin.java:402)
    at net.runelite.client.plugins.discord.DiscordPlugin.onGameStateChanged(DiscordPlugin.java:210)
    at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
    at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:62)
    at io.reactivex.internal.operators.observable.ObservableFilter$FilterObserver.onNext(ObservableFilter.java:52)
    at com.jakewharton.rxrelay2.PublishRelay$PublishDisposable.onNext(PublishRelay.java:180)
    at com.jakewharton.rxrelay2.PublishRelay.accept(PublishRelay.java:145)
    at com.jakewharton.rxrelay2.SerializedRelay.accept(SerializedRelay.java:57)
    at net.runelite.client.eventbus.EventBus.post(EventBus.java:102)
    at net.runelite.client.callback.Hooks.post(Hooks.java:161)
    at client.gameStateChanged(client.java:1112)
    at dh.fp(dh.java:1752)
    at client.ae(client.java:1594)
    at bg.av(bg.java:355)
    at bg.run(bg.java:334)
    at java.lang.Thread.run
```

**Comment by SRLJustin** [comment]
same issue as #1667 ?
