### ISSUE TITLE
playerscouter: NoSuchElementException

### ISSUE THREAD

**Issue by Owain94** [open-osrs/runelite#1950]
```java
java.util.NoSuchElementException: null
    at java.util.LinkedHashMap$LinkedHashIterator.nextNode
    at java.util.LinkedHashMap$LinkedEntryIterator.next
    at java.util.LinkedHashMap$LinkedEntryIterator.next
    at net.runelite.client.plugins.playerscouter.PlayerScouter.getEntry(PlayerScouter.java:448)
    at net.runelite.client.plugins.playerscouter.PlayerScouter.scoutPlayer(PlayerScouter.java:579)
    at net.runelite.client.plugins.playerscouter.PlayerScouter.lambda$onGameTick$0(PlayerScouter.java:201)
    at java.lang.Iterable.forEach
    at net.runelite.client.plugins.playerscouter.PlayerScouter.onGameTick(PlayerScouter.java:190)
    at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
    at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:62)
    at io.reactivex.internal.operators.observable.ObservableFilter$FilterObserver.onNext(ObservableFilter.java:52)
    at com.jakewharton.rxrelay2.PublishRelay$PublishDisposable.onNext(PublishRelay.java:180)
    at com.jakewharton.rxrelay2.PublishRelay.accept(PublishRelay.java:145)
    at com.jakewharton.rxrelay2.SerializedRelay.accept(SerializedRelay.java:57)
    at net.runelite.client.eventbus.EventBus.post(EventBus.java:102)
    at net.runelite.client.callback.Hooks.clientMainLoop(Hooks.java:179)
    at client.draw(client.java:1490)
    at client.au(client.java)
    at bg.am(bg.java:381)
    at bg.run(bg.java:335)
    at java.lang.Thread.run
```

**Comment by Ganom** [comment]
Fixed by #1952 , will close when merged.
