### ISSUE TITLE
playerscouter: NPE

### ISSUE THREAD

**Issue by Owain94** [open-osrs/runelite#1972]
```java
java.lang.NullPointerException: null
    at java.util.Objects.requireNonNull
    at net.runelite.client.plugins.playerscouter.PlayerScouter.location(PlayerScouter.java:646)
    at net.runelite.client.plugins.playerscouter.PlayerScouter.update(PlayerScouter.java:291)
    at net.runelite.client.plugins.playerscouter.PlayerScouter.lambda$onGameTick$0(PlayerScouter.java:192)
    at java.lang.Iterable.forEach
    at net.runelite.client.plugins.playerscouter.PlayerScouter.onGameTick(PlayerScouter.java:190)
    at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
    at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:62)
    at io.reactivex.internal.operators.observable.ObservableFilter$FilterObserver.onNext(ObservableFilter.java:52)
    at com.jakewharton.rxrelay2.PublishRelay$PublishDisposable.onNext(PublishRelay.java:180)
    at com.jakewharton.rxrelay2.PublishRelay.accept(PublishRelay.java:145)
    at com.jakewharton.rxrelay2.SerializedRelay.accept(SerializedRelay.java:57)
    at net.runelite.client.eventbus.EventBus.post(EventBus.java:102)
    at net.runelite.client.callback.Hooks.clientMainLoop(Hooks.java:179)
    at client.draw(client.java:1490)
    at client.au(client.java)
    at bg.am(bg.java:381)
    at bg.run(bg.java:335)
    at java.lang.Thread.run
```

**Comment by Ganom** [comment]
Fixed in #1952
