### ISSUE TITLE
maxhit: NPE

### ISSUE THREAD

**Issue by Owain94** [open-osrs/runelite#1977]
```java
java.lang.NullPointerException: null
    at net.runelite.client.plugins.maxhit.calculators.MagicMaxHitCalculator.calculate(MagicMaxHitCalculator.java:81)
    at net.runelite.client.plugins.maxhit.calculators.MaxHitCalculator.getMaxHit(MaxHitCalculator.java:137)
    at net.runelite.client.plugins.maxhit.MaxHitPlugin.updateMaxHitWidget(MaxHitPlugin.java:114)
    at net.runelite.client.plugins.maxhit.MaxHitPlugin.onItemContainerChanged(MaxHitPlugin.java:83)
    at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
    at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:62)
    at io.reactivex.internal.operators.observable.ObservableFilter$FilterObserver.onNext(ObservableFilter.java:52)
    at com.jakewharton.rxrelay2.PublishRelay$PublishDisposable.onNext(PublishRelay.java:180)
    at com.jakewharton.rxrelay2.PublishRelay.accept(PublishRelay.java:145)
    at com.jakewharton.rxrelay2.SerializedRelay.accept(SerializedRelay.java:57)
    at net.runelite.client.eventbus.EventBus.post(EventBus.java:102)
    at net.runelite.client.util.DeferredEventBus.replay(DeferredEventBus.java:64)
    at net.runelite.client.callback.Hooks.clientMainLoop(Hooks.java:177)
    at client.draw(client.java:1490)
    at client.au(client.java)
    at bg.am(bg.java:381)
    at bg.run(bg.java:335)
    at java.lang.Thread.run
```

**Comment by Ganom** [comment]
```java
			if (autoCastSpell == null)
			{
				return 0.0;
			}
```
