### ISSUE TITLE
suppliestracker: ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Owain94** [open-osrs/runelite#1996]
```java
java.lang.ArrayIndexOutOfBoundsException: Index 18 out of bounds for length 3
    at net.runelite.client.plugins.suppliestracker.SuppliesTrackerPlugin.onItemContainerChanged(SuppliesTrackerPlugin.java:406)
    at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
    at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:62)
    at io.reactivex.internal.operators.observable.ObservableFilter$FilterObserver.onNext(ObservableFilter.java:52)
    at com.jakewharton.rxrelay2.PublishRelay$PublishDisposable.onNext(PublishRelay.java:180)
    at com.jakewharton.rxrelay2.PublishRelay.accept(PublishRelay.java:145)
    at com.jakewharton.rxrelay2.SerializedRelay.accept(SerializedRelay.java:57)
    at net.runelite.client.eventbus.EventBus.post(EventBus.java:102)
    at net.runelite.client.util.DeferredEventBus.replay(DeferredEventBus.java:64)
    at net.runelite.client.callback.Hooks.clientMainLoop(Hooks.java:177)
    at client.draw(client.java:1490)
    at client.au(client.java)
    at bg.am(bg.java:381)
    at bg.run(bg.java:335)
    at java.lang.Thread.run
```

**Comment by Crystalknoct** [comment]
#2167 Aswell as previous updates to supply tracker seem to have fixed as I havnt had this error since myself. Can anyone else clarify aswell?

**Comment by Dyldozer** [comment]
> #2167 Aswell as previous updates to supply tracker seem to have fixed as I havnt had this error since myself. Can anyone else clarify aswell?

Yeah the additions to on menu fix it awhile ago

**Comment by Crystalknoct** [comment]
@Owain94 Deem this closed?
