### ISSUE TITLE
Party Plugin Broken

### ISSUE THREAD

**Issue by edgar1016** [open-osrs/runelite#2289]
**Describe the bug**
The client fails to create a party. I get the following message when launched is clicked.
![image](https://user-images.githubusercontent.com/13511581/73159118-f6570880-40a2-11ea-9b8a-aa46e297b2b8.png)

**To Reproduce**
Attempt to start a party.

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 1.6.4
 - OpenOsRS version: 2.1.23
 - Launcher version: 2.0.5

I get the following error in the logs
> `2020-01-27 00:42:25 [pool-4-thread-1] ERROR net.runelite.client.RuneLite - Uncaught exception:
kotlin.KotlinNullPointerException: null
	at okhttp3.internal.ws.RealWebSocket.runWriter(RealWebSocket.kt:398)
	at okhttp3.internal.ws.RealWebSocket.send(RealWebSocket.kt:352)
	at okhttp3.internal.ws.RealWebSocket.send(RealWebSocket.kt:332)
	at net.runelite.client.ws.WSClient.send(WSClient.java:137)
	at net.runelite.client.ws.WSClient.connect(WSClient.java:109)
	at net.runelite.client.ws.WSClient.changeSession(WSClient.java:90)
	at net.runelite.client.ws.PartyService.changeParty(PartyService.java:118)
	at net.runelite.client.plugins.discord.DiscordPlugin.onDiscordJoinGame(DiscordPlugin.java:267)
	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
	at io.reactivex.internal.operators.observable.ObservableDoFinally$DoFinallyObserver.onNext(ObservableDoFinally.java:80)
	at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:62)
	at io.reactivex.internal.operators.observable.ObservableFilter$FilterObserver.onNext(ObservableFilter.java:52)
	at com.jakewharton.rxrelay2.PublishRelay$PublishDisposable.onNext(PublishRelay.java:180)
	at com.jakewharton.rxrelay2.PublishRelay.accept(PublishRelay.java:145)
	at com.jakewharton.rxrelay2.SerializedRelay.accept(SerializedRelay.java:57)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:122)
	at net.runelite.client.discord.DiscordService.joinGame(DiscordService.java:218)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.invokeCallback(CallbackReference.java:520)
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.callback(CallbackReference.java:551)
	at com.sun.jna.Native.invokeVoid(Native Method)
	at com.sun.jna.Function.invoke(Function.java:415)
	at com.sun.jna.Function.invoke(Function.java:361)
	at com.sun.jna.Library$Handler.invoke(Library.java:265)
	at com.sun.proxy.$Proxy26.Discord_RunCallbacks(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2020-01-27 00:42:25 [OkHttp https://api.runelite.net/...] INFO  net.runelite.client.ws.WSClient - Websocket okhttp3.internal.ws.RealWebSocket@c815cd1 opened
`

**Comment by ThatGamerBlue** [comment]
this specific bug is fixed, but the plugin itself is still broken... soon™️
