### ISSUE TITLE
Polybar integration

### ISSUE THREAD

**Issue by Crystalknoct** [open-osrs/runelite#2384]
Not sure what its exact use is from what I read it changes something with menus. Anyways got this error even after a restart right after installing. 
`2020-02-26 02:05:29 [Client] ERROR n.r.c.p.p.PolybarIntegrationPlugin - Failed to write to file /tmp/rl_state
2020-02-26 02:05:29 [pool-3-thread-1] ERROR n.r.c.p.p.PolybarIntegrationPlugin - Execution of polybar-msg command threw exception
java.io.IOException: Cannot run program "polybar-msg": CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at net.runelite.client.plugins.polybarintegration.PolybarIntegrationPlugin.lambda$notifyPolybar$0(PolybarIntegrationPlugin.java:317)
	at net.runelite.client.util.RunnableExceptionLogger.run(RunnableExceptionLogger.java:41)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessImpl.create(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:420)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:151)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 9 common frames omitted`

**Comment by Owain94** [comment]
Are you actually on a linux distro and do you have polybar installed?

**Comment by Crystalknoct** [comment]
Sorry this can be closed I pulled a silly.
