### ISSUE TITLE
Quest Helper from Plugin Hub not loading Quests

### ISSUE THREAD

**Issue by rmwyatt** [open-osrs/runelite#2854]
Since OPRS doesn't sync with the online Runelite settings.properties file, would that cause an issues with quest helper saying I need to be logged in to view quests: see attached photo.

![unknown](https://user-images.githubusercontent.com/60189269/98743533-d5cc1680-2375-11eb-8465-261eb8496f7a.png)

Earlier, it showed the quests, but when I clicked on one, its as if the little arrows didn't do anything. So, I turned off and turned back on the plugin, uninstalled > restarted client > reinstalled >restarted client and I'm at that screenshot.

I made sure the issue was not also apparent while using the Runelite Client.

**Comment by zeruth** [comment]
There is likely an error in your logs that halts the plugin. and it just doesn't process after that.

Post a link to your client log found in %USER%/.runelite/logs/  and try to make sure it contains info related to questhelper

**Comment by rmwyatt** [comment]
2020-11-10 13:21:22 [Client] ERROR net.runelite.client.RuneLite - Uncaught exception:
io.reactivex.rxjava3.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.lang.reflect.InvocationTargetException
	at io.reactivex.rxjava3.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
	at io.reactivex.rxjava3.internal.observers.LambdaObserver.onError(LambdaObserver.java:83)
	at io.reactivex.rxjava3.internal.observers.LambdaObserver.onNext(LambdaObserver.java:67)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableDoFinally$DoFinallyObserver.onNext(ObservableDoFinally.java:80)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:63)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableFilter$FilterObserver.onNext(ObservableFilter.java:52)
	at com.jakewharton.rxrelay3.PublishRelay$PublishDisposable.onNext(PublishRelay.java:179)
	at com.jakewharton.rxrelay3.PublishRelay.accept(PublishRelay.java:144)
	at com.jakewharton.rxrelay3.SerializedRelay.accept(SerializedRelay.java:57)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:115)
	at net.runelite.client.callback.Hooks.clientMainLoop(Hooks.java:193)
	at client.draw(Client.java:1519)
	at client.ak(Client.java)
	at ba.d(GameShell.java:361)
	at ba.run(GameShell.java:315)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.GeneratedMethodAccessor278.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.runelite.client.plugins.Plugin.lambda$findSubscriptions$1(Plugin.java:102)
	at io.reactivex.rxjava3.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
	... 13 common frames omitted
Caused by: java.lang.NullPointerException: null
	at com.questhelper.quests.shadowofthestorm.SearchKilns.setupSteps(SearchKilns.java:87)
	at com.questhelper.steps.DetailedOwnerStep.<init>(DetailedOwnerStep.java:63)
	at com.questhelper.quests.shadowofthestorm.SearchKilns.<init>(SearchKilns.java:49)
	at com.questhelper.quests.shadowofthestorm.ShadowOfTheStorm.setupSteps(ShadowOfTheStorm.java:264)
	at com.questhelper.quests.shadowofthestorm.ShadowOfTheStorm.loadSteps(ShadowOfTheStorm.java:92)
	at com.questhelper.questhelpers.BasicQuestHelper.startUp(BasicQuestHelper.java:47)
	at com.questhelper.QuestHelperPlugin.startUpQuest(QuestHelperPlugin.java:459)
	at com.questhelper.QuestHelperPlugin.onGameTick(QuestHelperPlugin.java:202)
	... 18 common frames omitted

**Comment by rmwyatt** [comment]
[client.log](https://github.com/open-osrs/runelite/files/5520727/client.log)

**Comment by zeruth** [comment]
Fixed in https://github.com/Owain94/OpenOSRS-RL-hub/commit/ed03d7a6bf881c0090181b420b9b3c76aad664d4
