### ISSUE TITLE
Client freezes every 5-10 minutes

### ISSUE THREAD

**Issue by zbabyg** [open-osrs/runelite#3123]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/open-osrs/runelite/search?type=Issues)

**Describe the bug**
Every 5-10 minutes my client freezes for a few seconds, generally about 5 seconds or so. When they game unfreezes, I have usually died to a number of hit splats, meaning it is not a server lag and is only happening to me. I have no issues at all with Runelite, meaning that this problem is unique to OpenOSRS. I do not have any externals whatsoever. I've redownloaded, changed the name of the plugins folder, and updated my AMD graphic card drivers.

**To Reproduce**
1. Open OSRS
2. Play for 10 minutes or so

**Expected behavior**
Screen should not freeze.

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: Windows
 - OpenOSRS version: Most recent, downloaded today
 - Launcher version: 2.2.0

**Additional context**

**Comment by zbabyg** [comment]
2022-01-26 16:50:47 [RuneLite] INFO  net.runelite.client.RuneLite - OpenOSRS 4.19.0 (RuneLite version 1.8.10, launcher version 2.2.0) starting up, args: none
2022-01-26 16:50:49 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached vanilla client
2022-01-26 16:50:49 [Preloader] INFO  net.runelite.client.rs.ClientLoader - injected-client 4.19.0
2022-01-26 16:50:50 [RuneLite] INFO  n.r.client.account.SessionManager - No session file exists
2022-01-26 16:50:50 [RuneLite] INFO  org.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
2022-01-26 16:50:50 [RuneLite] INFO  org.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
2022-01-26 16:50:50 [RuneLite] INFO  org.pf4j.DefaultPluginManager - PF4J version 3.6.0 in 'deployment' mode
2022-01-26 16:50:50 [RuneLite] INFO  org.jgroups.JChannel - local_addr: 1103816a-2634-eb40-fdef-ec8292fadc96, name: c2b71771-2ebd-4d9a-acf2-cc3d83ee3ace
2022-01-26 16:50:52 [RuneLite] INFO  org.jgroups.protocols.pbcast.GMS - c2b71771-2ebd-4d9a-acf2-cc3d83ee3ace: no members discovered after 2015 ms: creating cluster as coordinator
2022-01-26 16:50:52 [RuneLite] ERROR n.r.c.p.OPRSExternalPluginManager - Error loading external repositories. They have been reset.
2022-01-26 16:50:52 [RuneLite] WARN  n.r.c.p.OPRSExternalPf4jPluginManager - No plugins
2022-01-26 16:50:53 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2022-01-26 16:50:54 [RuneLite] INFO  n.r.c.p.OPRSExternalPluginManager - External plugin instantiation took 1ms
2022-01-26 16:50:54 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2022-01-26 16:50:56 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 8875ms. Uptime: 18368ms
2022-01-26 16:50:56 [pool-3-thread-1] INFO  n.r.client.discord.DiscordService - Discord RPC service is ready with user GbabyZ.
2022-01-26 16:50:56 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,0,0,1920x1040,layout=java.awt.BorderLayout,title=OpenOSRS,resizable,maximized,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,1920x1040,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@5551065c,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2022-01-26 16:50:58 [Client] INFO  n.r.client.plugins.gpu.GpuPlugin - Using device: AMD Radeon RX 5700 XT
2022-01-26 16:50:58 [Client] INFO  n.r.client.plugins.gpu.GpuPlugin - Using driver: 4.6.14802 Compatibility Profile Context 22.1.2 30.0.14023.3004
2022-01-26 17:01:06 [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - Error during overlay rendering
java.lang.IllegalArgumentException: Color parameter outside of expected range: Green Blue
	at java.desktop/java.awt.Color.testColorValueRange(Unknown Source)
	at java.desktop/java.awt.Color.<init>(Unknown Source)
	at net.runelite.client.util.ColorUtil.colorLerp(ColorUtil.java:111)
	at net.runelite.client.plugins.prayer.PrayerDoseOverlay.render(PrayerDoseOverlay.java:151)
	at net.runelite.client.ui.overlay.OverlayRenderer.safeRender(OverlayRenderer.java:793)
	at net.runelite.client.ui.overlay.OverlayRenderer.renderOverlays(OverlayRenderer.java:287)
	at net.runelite.client.ui.overlay.OverlayRenderer.renderAfterInterface(OverlayRenderer.java:228)
	at net.runelite.client.callback.Hooks.drawInterface(Hooks.java:506)
	at client.postRenderWidgetLayer(Client.java:1943)
	at dc.jl(class118.java:10847)
	at d.jp(class12.java:10380)
	at client.gg(Client.java:5030)
	at client.copy$draw(Client.java:1913)
	at client.y(Client.java:1803)
	at am.k(GameEngine.java:361)
	at am.run(GameEngine.java:315)
	at java.base/java.lang.Thread.run(Unknown Source)
