### ISSUE TITLE
seed vault causing client to crash 

### ISSUE THREAD

**Issue by w355osrs** [open-osrs/runelite#465]
**Describe the bug**
Sometimes depositing seeds into seed vault (deposit all) will cause the game to crash. Find its happened three times now when I have a lot of seeds in inventory (with seed packs). 

2019-05-31 22:21:04 [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
2019-06-01 01:32:28 [Client] ERROR net.runelite.client.RuneLite - Game crash: null

**Comment by Lucwousin** [comment]
We're not gonna be able to know what the problem is from just those 2 messages. Was there no stacktrace other than this?

**Comment by SRLJustin** [comment]
Unable to replicate, spent 20 minutes trying to get my client to crash

**Comment by w355osrs** [comment]
@SRLJustin @Lucwousin @ThatGamerBlue 

2019-06-05 10:19:04 [RuneLite] INFO  net.runelite.client.rs.ClientLoader - Patched 339 classes
2019-06-05 10:19:04 [RuneLite] INFO  net.runelite.client.rs.ClientLoader - client-patch 218477404.144
2019-06-05 10:19:07 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2019-06-05 10:19:08 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,552,249,817x542,layout=java.awt.BorderLayout,title=RuneLite,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,8,31,801x503,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2019-06-05 10:19:11 [AWT-EventQueue-0] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2019-06-05 10:19:12 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 10950ms. Uptime: 19520ms
2019-06-05 10:19:13 [pool-3-thread-1] INFO  n.r.client.discord.DiscordService - Discord RPC service is ready with user W355.
2019-06-05 11:43:25 [OkHttp https://crystalmathlabs.com/...] WARN  n.r.c.p.c.CrystalMathLabs - Error submitting CML update, caused by timeout.
2019-06-05 13:30:27 [AWT-EventQueue-0] WARN  n.runelite.client.menus.MenuManager - You shouldn't try swapping an entry for itself
2019-06-05 13:30:44 [AWT-EventQueue-0] WARN  n.runelite.client.menus.MenuManager - You shouldn't try swapping an entry for itself
2019-06-05 13:53:13 [OkHttp https://crystalmathlabs.com/...] WARN  n.r.c.p.c.CrystalMathLabs - Error submitting CML update, caused by timeout.
2019-06-05 19:49:53 [RuneLite] INFO  net.runelite.client.rs.ClientLoader - Patched 339 classes
2019-06-05 19:49:53 [RuneLite] INFO  net.runelite.client.rs.ClientLoader - client-patch 218477404.144
2019-06-05 19:49:56 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2019-06-05 19:49:57 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,552,249,817x542,layout=java.awt.BorderLayout,title=RuneLite,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,8,31,801x503,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2019-06-05 19:50:01 [AWT-EventQueue-0] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2019-06-05 19:50:01 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 15604ms. Uptime: 20123ms
2019-06-05 19:50:53 [pool-3-thread-1] INFO  n.r.client.discord.DiscordService - Discord RPC service is ready with user W355.
2019-06-05 20:11:24 [Client] ERROR net.runelite.client.RuneLite - Game crash: null
java.lang.ArithmeticException: / by zero
	at dl.ac(dl.java:2320)
	at gy.q(gy.java:417)
	at l.f(l.java:354)
	at ir.m(ir.java:96)
	at client.gs(client.java:3622)
	at client.aw(client.java:1621)
	at ba.ar(ba.java:393)
	at ba.run(ba.java:372)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Lucwousin** [comment]
Reopening as this seems to be the same as this
```2019-09-03 00:43:52 [Client] ERROR n.runelite.client.eventbus.EventBus - Error in eventbus: null
2019-09-03 00:43:52 [Client] ERROR n.runelite.client.eventbus.EventBus - java.lang.NullPointerException
    at net.runelite.client.plugins.bank.ContainerCalculation.hashItems(ContainerCalculation.java:103)
    at net.runelite.client.plugins.bank.ContainerCalculation.calculate(ContainerCalculation.java:54)
    at net.runelite.client.plugins.bank.BankPlugin.updateSeedVaultTotal(BankPlugin.java:329)
    at net.runelite.client.plugins.bank.BankPlugin.onWidgetLoaded(BankPlugin.java:228)
    at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
    at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:62)
    at io.reactivex.internal.operators.observable.ObservableFilter$FilterObserver.onNext(ObservableFilter.java:52)
    at com.jakewharton.rxrelay2.PublishRelay$PublishDisposable.onNext(PublishRelay.java:180)
    at com.jakewharton.rxrelay2.PublishRelay.accept(PublishRelay.java:145)
    at com.jakewharton.rxrelay2.SerializedRelay.accept(SerializedRelay.java:57)
    at net.runelite.client.eventbus.EventBus.post(EventBus.java:81)
    at net.runelite.client.callback.Hooks.post(Hooks.java:159)
    at ae.ag(ae.java:983)
    at ci.jl(ci.java:10485)
    at client.hc(client.java:5467)
    at client.fc(client.java:2773)
    at client.aj(client.java:1280)
    at bw.o(bw.java:365)
    at bw.run(bw.java:344)
    at java.lang.Thread.run(Thread.java:748)
